// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

/**
 * The dashboard uses the flat config generated by `@nuxt/eslint` rather than the
 * repo-root config: it needs the Vue parser, Nuxt's auto-imported globals and the
 * `app/` directory conventions. The root `eslint.config.mjs` therefore ignores
 * `apps/**`.
 */
export default withNuxt({
  ignores: [
    'app/components/ui/**',
    '.nuxt/**',
    '.output/**',
    'dist/**',
    'node_modules/**',
  ],
})
